-- Found ament_cmake: 2.0.3 (/opt/ros/iron/share/ament_cmake/cmake)
-- Found ament_lint_auto: 0.14.2 (/opt/ros/iron/share/ament_lint_auto/cmake)
-- Found rosidl_default_generators: 1.5.0 (/opt/ros/iron/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found rosidl_adapter: 4.0.1 (/opt/ros/iron/share/rosidl_adapter/cmake)
[31mCMake Error at /opt/ros/iron/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  wireless_lidar --arguments-file
  /home/mr-cheng/Desktop/Car/Wireless_Lidar/extra_packages/build/wireless_lidar/rosidl_adapter__arguments__wireless_lidar.json
  --output-dir
  /home/mr-cheng/Desktop/Car/Wireless_Lidar/extra_packages/build/wireless_lidar/rosidl_adapter/wireless_lidar
  --output-file
  /home/mr-cheng/Desktop/Car/Wireless_Lidar/extra_packages/build/wireless_lidar/rosidl_adapter/wireless_lidar.idls)
  returned error code 1:

  Error processing 'pointdata[16] data' of 'wireless_lidar/LidarData':
  ''pointdata' is an invalid message name.  It should have the pattern
  '^[A-Z][A-Za-z0-9]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 521, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 278, in __init__
      super(Type, self).__init__(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 206, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'pointdata' is an invalid
  message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /opt/ros/iron/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:28 (rosidl_generate_interfaces)

[0m
-- Configuring incomplete, errors occurred!
See also "/home/mr-cheng/Desktop/Car/Wireless_Lidar/extra_packages/build/wireless_lidar/CMakeFiles/CMakeOutput.log".
